# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

exclude: 'docs|.git|.tox'
default_stages: [ commit ]

repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v3.4.0
        hooks:
            -   id: check-added-large-files
            -   id: check-yaml
            -   id: check-json
            -   id: check-case-conflict
            -   id: check-executables-have-shebangs
            -   id: check-merge-conflict
            -   id: check-symlinks
            -   id: trailing-whitespace
                exclude_types: [ svg ]
            -   id: end-of-file-fixer
                exclude_types: [ svg ]
            -   id: check-yaml

    -   repo: git://github.com/asottile/reorder_python_imports
        rev: v1.3.4
        hooks:
            -   id: reorder-python-imports
                language_version: 'python3.9'
                args:
                    - --py3-plus

    -   repo: https://github.com/psf/black.git
        rev: 20.8b1
        hooks:
            -   id: black
                language_version: python3.9
                files: src/

    -   repo: https://gitlab.com/pycqa/flake8
        rev: 3.7.9
        hooks:
            -   id: flake8

    -   repo: https://github.com/pre-commit/mirrors-mypy
        rev: 'v0.812'
        hooks:
            -   id: mypy
