[build-system]
requires = ["uv_build>=0.5"]
build-backend = "uv_build"

[project]
name = "kupala"
version = "0.0.0"
description = "A web framework that gets out of your way."
readme = "README.md"
authors = [{ name = "alex.oleshkevich", email = "alex.oleshkevich@gmail.com" }]
requires-python = ">=3.14"
dependencies = [
    "jinja2>=3.0",
    "python-multipart>=0.0.20",
    "click>=8.1",
    "asgiref>=3.11.1",
    "python-dotenv>=1.2.2",
]

[dependency-groups]
dev = [
    "pytest>=8.3.4",
    "pytest-asyncio>=0.25.3",
    "pytest-cov>=6.0.0",
]
testing = [
    "mypy>=2.0",
    "pre-commit>=4.1.0",
]

[tool.uv.build-backend]
module-name = "kupala"
module-root = ""

[tool.mypy]
files = ["kupala", "tests"]
pretty = true
strict = true
show_error_context = true
show_column_numbers = true
show_error_codes = true
implicit_reexport = true
warn_no_return = false
disallow_subclassing_any = false
ignore_missing_imports = true

[tool.ruff]
line-length = 120
indent-width = 4
exclude = ['var', '.venv', '.git']

[tool.ruff.lint]
fixable = ["ALL"]

[tool.pytest.ini_options]
asyncio_mode = 'auto'
asyncio_default_fixture_loop_scope = 'session'
filterwarnings = [
    "ignore::DeprecationWarning:pytest_asyncio",
]
norecursedirs = [
    "node_modules",
    "assets",
    "dist",
    ".git",
    "var",
    "*/migrations/*",
    "*/static/*",
    "docs",
    ".venv",
]
addopts = "--tb=short -s --no-cov-on-fail"
testpaths = ["tests"]

[tool.coverage.run]
branch = false
parallel = true
source = ["kupala", "tests"]
omit = [".venv/*", ".git/*", "*/__main__.py", "examples"]

[tool.coverage.report]
fail_under = 100
show_missing = true
skip_covered = true
skip_empty = true

exclude_also = [
    "raise AssertionError",
    "raise NotImplementedError",
    "def __repr__",
    "if self\\.debug",
    "if 0:",
    "if False:",
    "if __name__ == .__main__.:",
    "@(abc\\.)?abstractmethod",
]

[tool.coverage.html]
directory = "var/coverage/html_report"
